
services:
  frontend:
    image: node:20
    container_name: vpn-site-frontend
    working_dir: /app
    volumes:
      - ./vpn-ui:/app
    ports:
      - '5173:5173'
    command: sh -c "npm install && npm run dev"